(ns reagent-timer-demo.core
  (:require [reagent.core :as reagent]
            [clojure.string :as string]
            [goog.string :as gstring]
            [cljsjs.react-timer-mixin]))

(def TimerMixin js/TimerMixin)

(def data ["Aliquip occaecat reprehenderit reprehenderit consectetur exercitation nisi laborum proident quis qui exercitation proident minim ullamco. In laboris ut mollit culpa reprehenderit veniam sunt velit aute eiusmod. Et do eiusmod laborum esse Lorem nisi elit elit incididunt. Aute excepteur ex enim cupidatat nisi velit eiusmod nisi laboris. Magna in pariatur Lorem cupidatat dolor cupidatat ad dolor ullamco. Nostrud aliquip ea adipisicing laboris labore aute laboris dolore.",
           "Laboris ea sint pariatur sint occaecat ea velit aliquip id fugiat deserunt ut Lorem. Nisi id quis nostrud ea deserunt cupidatat fugiat. Veniam magna cupidatat ex duis adipisicing excepteur aliquip proident cupidatat. Tempor aliqua aute nulla reprehenderit. Et ex pariatur enim id ea laboris occaecat culpa esse ea ullamco. Reprehenderit consequat sint et id.",
           "Anim tempor proident consequat eiusmod exercitation aliqua non sit. Aliquip tempor ipsum anim tempor elit consequat adipisicing. Id occaecat ex enim et magna voluptate dolore fugiat duis commodo veniam anim. Exercitation id aute adipisicing dolore fugiat duis amet incididunt. Qui id fugiat sit mollit adipisicing consectetur aliqua ullamco qui minim. Sit non cupidatat ipsum esse officia in duis consequat ut est.",
           "Nisi est eiusmod qui proident occaecat velit elit consectetur reprehenderit irure nisi. Non amet in nostrud pariatur tempor aliqua laboris enim est excepteur anim duis dolor. Voluptate labore excepteur pariatur velit veniam excepteur elit pariatur sint commodo. Aliqua eiusmod amet ex nisi officia esse. Sunt minim cillum in in mollit exercitation voluptate incididunt. Exercitation ex magna consectetur id sint aliqua commodo qui pariatur ut non Lorem. Eiusmod proident labore non dolore ad aute labore adipisicing aliquip.",
           "Excepteur officia culpa quis ut minim incididunt aute tempor. Nisi elit aute Lorem sit sit duis do consequat ipsum fugiat cillum eiusmod ad. Eiusmod pariatur nostrud non non amet irure culpa nulla. Anim magna nisi mollit duis excepteur ex esse incididunt Lorem duis magna officia. Nostrud anim aliqua irure consequat consectetur est non do commodo deserunt ex eiusmod veniam mollit. Nostrud consequat velit in qui adipisicing esse consectetur sunt consequat excepteur sint ipsum. Ad ea irure mollit consectetur nisi sit nisi ex voluptate voluptate magna adipisicing dolore.",
           "Velit nulla tempor in non culpa quis incididunt proident quis irure cillum ut. Mollit do occaecat Lorem nisi ea dolore aliquip commodo sunt id nostrud Lorem ut. Sit incididunt sit fugiat commodo exercitation esse est qui culpa occaecat. Laboris consectetur qui officia pariatur laboris quis esse dolore ad ipsum sit exercitation.",
           "Reprehenderit elit sint dolore est reprehenderit. Labore aliqua do voluptate cupidatat nostrud magna id sunt aliquip et consectetur est. Qui consectetur esse ea sit duis officia tempor. Tempor magna qui elit eiusmod incididunt anim est in. Commodo Lorem ipsum non dolore consequat pariatur sint amet et non anim sit. Nisi laborum culpa ullamco culpa laboris incididunt cupidatat qui dolore amet.",
           "Nostrud aliquip adipisicing culpa cillum velit incididunt officia dolor consectetur deserunt excepteur est. Dolor incididunt Lorem magna duis pariatur laborum adipisicing consectetur consectetur aliquip qui laborum amet enim. Dolore quis tempor labore anim in. Reprehenderit esse labore velit consectetur. Ullamco pariatur magna exercitation ea id excepteur nulla aliqua. Nostrud nostrud tempor nisi aute nulla occaecat cupidatat. Exercitation pariatur est veniam ut reprehenderit proident id velit.",
           "Qui excepteur anim minim exercitation nisi. Ipsum aliquip dolore non minim esse esse quis. Aliqua nulla laboris labore ullamco pariatur sint dolor eiusmod dolor nostrud. In eiusmod id et ex laboris est ad officia irure est aute cupidatat. Lorem veniam consectetur deserunt ipsum Lorem.",
           "Consectetur duis in tempor sint. Laboris id ex ullamco eu aliquip minim eiusmod non aliqua. Eiusmod non ullamco non ex deserunt labore enim tempor voluptate et minim incididunt. Voluptate duis sunt deserunt nulla sint aliquip magna laboris dolore. Do magna eiusmod fugiat nostrud sit consectetur mollit fugiat Lorem elit nisi minim. Et consectetur esse eu sint ea cillum dolor nostrud occaecat ipsum reprehenderit qui. Ea mollit officia est eu est laborum velit aliqua id officia.",
           "Ipsum deserunt adipisicing elit incididunt aliqua ullamco ex duis incididunt. Veniam consectetur Lorem velit occaecat ea elit dolore esse qui voluptate. Amet aliquip occaecat nulla sunt nulla dolor magna cillum. Veniam quis aliqua sit labore elit ea ut reprehenderit irure ex. Ipsum elit laborum ea do sunt eiusmod cillum laborum eiusmod voluptate consequat aliqua eu elit. Do incididunt occaecat cupidatat ipsum aute id est et mollit labore ex consequat aute. Aliquip officia dolore non aliquip sint aute nulla cillum aute in non excepteur.",
           "Elit amet dolore sint occaecat. Dolor in reprehenderit incididunt nostrud. Mollit enim sunt labore non excepteur commodo dolore. Anim nulla proident sint sunt officia laboris amet aute et minim deserunt quis exercitation. Do culpa minim adipisicing cillum proident reprehenderit id nostrud. Tempor nostrud magna aliqua dolore adipisicing ipsum irure eiusmod ex quis amet laborum ipsum. Consectetur esse quis anim amet fugiat tempor adipisicing sunt quis fugiat.",
           "Lorem cillum nulla eu do excepteur consectetur commodo eu est Lorem. Nulla voluptate est consequat fugiat elit consectetur amet velit Lorem velit officia labore anim. Ex sit ut sint deserunt officia dolor ipsum et aliqua. Ut dolore mollit et consequat. Et officia enim laboris minim mollit ipsum est non duis elit nisi. Consectetur reprehenderit Lorem qui ipsum consectetur mollit proident fugiat nisi minim nulla consectetur pariatur. Consectetur cillum exercitation veniam sint ex cillum deserunt laborum exercitation ad consequat.",
           "Qui eu ea laborum do officia duis. Cupidatat sit pariatur aliqua quis aute id. Reprehenderit ad laborum deserunt et tempor sint fugiat consequat labore consequat occaecat do. Culpa sint sunt amet sint laboris aute ullamco velit qui. Lorem sit enim labore mollit enim sit cupidatat ea ex cillum. Do aliqua magna ut ex consectetur nisi est pariatur.",
           "Eiusmod dolor proident ullamco ullamco tempor dolor adipisicing sunt consequat voluptate deserunt. Esse minim eiusmod sunt officia aliquip dolor esse. Proident nisi id id minim occaecat labore reprehenderit reprehenderit sunt officia ullamco nostrud ullamco. Laborum non do elit voluptate commodo ullamco magna nisi duis fugiat officia nostrud. Ullamco officia pariatur veniam esse non Lorem. Fugiat aliquip irure non mollit enim adipisicing reprehenderit aliquip laborum. Irure ea reprehenderit dolor commodo consectetur ex in magna.",
           "Proident enim culpa incididunt do velit amet deserunt anim culpa nostrud amet ut elit. Reprehenderit ea esse magna enim id. Labore do incididunt tempor mollit ea exercitation dolor. Anim duis laborum sunt dolor tempor deserunt ea sunt sint. Laboris proident anim magna dolore sunt nostrud cillum veniam consectetur pariatur.",
           "Ullamco nostrud eu sunt adipisicing sint dolor quis consectetur velit. Est et dolor ipsum ut cillum sit nisi culpa ipsum proident eu minim. Adipisicing dolore ad do Lorem nulla pariatur reprehenderit magna nisi tempor labore cupidatat. Consectetur aliquip aliquip nisi consequat incididunt reprehenderit voluptate ad cillum proident.",
           "Lorem aute dolore excepteur eiusmod velit cupidatat dolor magna quis mollit consequat in ex magna. Duis do pariatur ipsum nulla laborum ad ad duis. Tempor mollit dolor adipisicing irure reprehenderit sunt esse aute pariatur mollit dolore. Occaecat non nulla cillum sit eu culpa sit exercitation. Duis excepteur eu eiusmod sit occaecat ea ea est non esse. Et nisi exercitation sint tempor labore excepteur anim mollit ex non nulla in nisi cillum. Sit ipsum aliqua occaecat nostrud irure et aliquip occaecat et consequat sunt nostrud sint.",
           "Laborum incididunt id Lorem elit culpa ex fugiat et culpa nisi nostrud eiusmod Lorem. Dolor ut reprehenderit excepteur occaecat veniam dolore. Officia id non ut in tempor exercitation proident est laborum et velit voluptate dolor. Laborum incididunt labore cillum irure aute labore. Ea consectetur commodo veniam magna cillum et sit amet elit consectetur dolore nulla.",
           "Laboris occaecat deserunt cillum id culpa eu ad sint enim Lorem. Minim aliqua commodo laborum do laboris. Pariatur deserunt do cupidatat excepteur occaecat aliquip enim consectetur sunt nulla culpa voluptate occaecat.",
           "Qui magna magna veniam sit aliqua pariatur pariatur ut ullamco ut aliquip labore. Duis incididunt sint ipsum qui duis reprehenderit sint et sit aliquip. Officia ad ipsum sunt culpa ea cillum reprehenderit id sunt reprehenderit fugiat ad. Est enim laboris culpa occaecat ipsum aute labore tempor nostrud enim ullamco nostrud anim. Nostrud deserunt duis nulla nostrud deserunt eiusmod officia culpa tempor. In cupidatat cillum deserunt in minim cillum aliquip cupidatat eiusmod laboris sunt nulla.",
           "Magna ut esse dolor do veniam quis culpa. Eu elit adipisicing aliquip commodo laborum adipisicing. Voluptate aute nostrud minim sit cupidatat adipisicing est nulla consectetur elit excepteur ea exercitation. Aliqua sint pariatur adipisicing mollit ullamco. Laboris ut occaecat qui incididunt sint sit quis sint non Lorem ea. Excepteur officia proident laboris laborum amet dolore aliqua occaecat amet aute aute consectetur.",
           "Quis consectetur laboris ipsum sit ex ex. Ex et amet sit sunt officia occaecat ipsum incididunt anim deserunt culpa reprehenderit ea id. Reprehenderit ullamco aliqua sint Lorem. Tempor nostrud qui adipisicing veniam anim nulla nulla ex fugiat dolore voluptate. Consequat elit sit exercitation anim nulla esse Lorem eiusmod aliqua adipisicing amet. Eiusmod sunt laborum fugiat excepteur nostrud sit nostrud consectetur laboris ullamco pariatur et incididunt officia.",
           "Consequat reprehenderit minim quis cupidatat commodo et sint consectetur. Cillum in aliqua commodo sint magna proident do mollit cillum anim incididunt excepteur. Elit in commodo tempor amet excepteur nisi adipisicing nulla officia qui commodo sit aliquip quis. Cupidatat sit culpa excepteur occaecat consectetur dolore nisi. Fugiat mollit esse ea enim consectetur.",
           "Consequat aliqua pariatur consectetur culpa pariatur reprehenderit ullamco dolor anim duis reprehenderit consectetur commodo sunt. Sint magna cupidatat excepteur Lorem eiusmod minim quis pariatur duis. Enim id eu dolore non et. Ipsum elit labore ex consequat in sunt ullamco do. Lorem eiusmod veniam anim exercitation cupidatat aliqua id cillum excepteur. Elit dolor dolore irure occaecat dolore do do excepteur mollit esse culpa magna id exercitation. Ex do nisi velit est ad fugiat laborum labore do pariatur quis aliqua ullamco nostrud.",
           "Adipisicing culpa enim labore magna elit sint incididunt amet. Pariatur consectetur ea officia ut eu proident ad voluptate ea. Non amet culpa et amet amet occaecat pariatur aliqua est excepteur do duis fugiat.",
           "Eiusmod ea fugiat enim non ipsum dolore mollit laborum reprehenderit veniam ex ut pariatur do. Ad cillum mollit ullamco sunt exercitation adipisicing minim deserunt pariatur nulla ea. Nulla consectetur incididunt incididunt eiusmod anim mollit in.",
           "Dolor esse duis est esse. Incididunt officia mollit laboris et consectetur mollit nisi minim. Non magna minim nulla id ad consequat ad sunt incididunt quis magna Lorem proident. Do ad labore est nostrud consequat duis aliquip qui labore adipisicing. Lorem labore reprehenderit laboris culpa deserunt amet dolor ipsum.",
           "Nostrud enim ad excepteur fugiat dolor eiusmod magna aute laboris aliquip. Ipsum officia voluptate adipisicing reprehenderit minim deserunt amet exercitation do ut deserunt anim. Enim proident velit proident voluptate occaecat tempor non elit. Proident eu ipsum aliqua mollit amet incididunt sit non aute nisi. Duis ex ex ex excepteur ea aute qui voluptate aliquip deserunt mollit enim.",
           "Aute mollit dolore in sunt. Exercitation mollit proident pariatur laborum sit. Aute ad occaecat esse eiusmod pariatur reprehenderit veniam deserunt Lorem.",
           "Velit ex Lorem quis deserunt in id officia deserunt pariatur magna. Ea in amet eu laborum anim commodo qui. Non excepteur deserunt ex reprehenderit fugiat.",
           "Ullamco elit sint in qui occaecat irure est et excepteur pariatur consectetur aute. Id dolor eu non qui sunt. Veniam commodo ad eiusmod eu laborum est anim proident.",
           "Ut adipisicing mollit ex voluptate aute consectetur Lorem consectetur tempor duis. Proident incididunt commodo quis pariatur mollit. Laboris labore in tempor qui esse. Consequat excepteur minim culpa quis culpa et aliquip. Elit excepteur ex veniam culpa consequat reprehenderit fugiat laboris eiusmod sit duis id elit.",
           "Culpa fugiat deserunt ad Lorem dolore ea ullamco anim. Magna pariatur cillum cupidatat minim adipisicing consequat labore esse id amet ipsum. Minim laboris eu sint ad aliqua deserunt consequat. Sit in ullamco veniam proident quis reprehenderit aliquip. Est cupidatat quis eiusmod sint voluptate sit voluptate veniam incididunt cupidatat Lorem non ex enim. Dolore incididunt in ex id adipisicing. Et adipisicing sint id dolore anim do aliquip id ea consectetur pariatur commodo pariatur.",
           "Magna proident ipsum mollit laborum elit laboris. Sunt laborum ea do et est amet veniam in adipisicing irure. Ut est consectetur sint aute velit in adipisicing consectetur. Culpa qui non nisi do aliquip ex eu. Aute sint cupidatat excepteur reprehenderit mollit mollit non.",
           "In velit ex ad duis commodo et eiusmod ad. Adipisicing pariatur non mollit ad nisi laborum sunt magna amet dolore in. Excepteur nisi occaecat esse ipsum in anim ut. Consequat nostrud nulla ut ut qui commodo fugiat consectetur consectetur. Enim minim do voluptate pariatur adipisicing incididunt ex reprehenderit proident ad ad nisi ea amet. Adipisicing ut sit dolore in do duis velit anim mollit tempor.",
           "Nostrud id veniam reprehenderit laboris nisi sint elit incididunt tempor. Non est proident nisi dolore est ipsum sint laborum elit laborum. Est cupidatat aliqua sunt id duis nostrud. Consectetur consequat laborum velit id. Tempor amet sit nostrud adipisicing. Labore nulla magna id cupidatat consequat voluptate excepteur laborum nisi.",
           "Minim reprehenderit fugiat consequat reprehenderit Lorem sunt qui Lorem reprehenderit deserunt reprehenderit velit. Sint dolor consectetur anim qui laboris occaecat adipisicing anim. Exercitation consectetur id nisi nisi irure pariatur enim. Pariatur irure commodo magna excepteur sit Lorem elit exercitation nisi proident. Labore id amet eu anim aliquip reprehenderit. Fugiat nisi reprehenderit laboris commodo est labore non non anim id.",
           "Reprehenderit cillum qui deserunt aliqua do duis. Aliqua minim quis et ea nostrud ipsum voluptate eu. Exercitation sit reprehenderit ipsum cillum sunt do mollit in. Incididunt labore cupidatat reprehenderit dolor pariatur ea. Commodo veniam dolor labore quis magna voluptate ad eiusmod velit labore.",
           "Laborum sit do occaecat labore labore. Qui mollit commodo quis aute nisi velit cillum voluptate laborum sint fugiat sint aute non. Aute ea voluptate sit sit.",
           "Ad sint minim irure do ad fugiat. Officia do sunt minim Lorem cupidatat elit occaecat nulla irure occaecat qui duis in. Consectetur sint ipsum pariatur ad labore non officia amet non velit ipsum commodo mollit tempor. Id aute cupidatat sint nulla mollit. Minim qui proident labore irure eu officia laboris qui eiusmod id deserunt amet esse exercitation.",
           "Esse duis nostrud consequat adipisicing minim reprehenderit eiusmod ipsum anim anim incididunt magna est excepteur. Eu fugiat anim id qui exercitation voluptate. Minim mollit eiusmod commodo reprehenderit veniam id quis officia sit laborum quis irure.",
           "Id labore laboris ex sunt nisi do velit nisi ad cillum commodo. Enim sint anim Lorem mollit ut aliqua pariatur anim aliquip. Sint proident esse ea enim fugiat irure ea duis officia velit fugiat commodo pariatur. Sint magna cillum aute incididunt officia non sit proident et sunt tempor laborum. Anim aliquip laborum ea dolore eiusmod aliqua amet esse sunt sunt officia id. Ullamco qui deserunt nulla culpa tempor sint reprehenderit sit sint.",
           "Mollit dolore aliqua deserunt voluptate adipisicing enim nulla consectetur nostrud aute. Magna tempor qui veniam eiusmod veniam minim sint quis. Enim ad reprehenderit labore anim esse tempor. Id fugiat enim irure dolore pariatur ex pariatur aliqua proident. Amet tempor dolore officia irure sint anim laborum et esse amet quis excepteur. Mollit reprehenderit ullamco cillum sint consectetur aliquip adipisicing. Nisi mollit deserunt pariatur pariatur sint occaecat culpa excepteur incididunt ipsum amet.",
           "Anim id sint est proident pariatur deserunt duis. Enim deserunt reprehenderit veniam qui consequat aliquip. Eiusmod voluptate ullamco occaecat amet mollit cillum velit incididunt in sint et ipsum dolor. Reprehenderit consectetur veniam duis anim anim incididunt non. Ut sit ad magna commodo proident fugiat reprehenderit sunt mollit. Cillum veniam do non cupidatat deserunt ad aliquip officia in. Consequat culpa aliqua excepteur mollit veniam quis ex nisi aliqua exercitation nostrud ipsum et.",
           "Deserunt ut consectetur cillum sunt duis nisi minim. Cupidatat reprehenderit excepteur nisi sit ex velit fugiat. Dolore consectetur et sint velit sunt officia nulla. Incididunt dolore reprehenderit cillum cillum nostrud. Consectetur sit minim velit deserunt ipsum dolore quis laborum ea est magna minim sunt. Veniam pariatur amet esse est.",
           "Tempor non incididunt aliquip esse ea aliquip est enim adipisicing id exercitation sint. Cupidatat aute tempor ea laboris eiusmod dolore reprehenderit ex officia. Ut nisi deserunt eu in veniam amet.",
           "Ea ipsum commodo nisi eiusmod magna voluptate. Dolore amet pariatur non aliqua consectetur cillum anim labore reprehenderit. Quis reprehenderit labore exercitation consectetur do. Nostrud tempor ullamco qui id ea officia ea adipisicing. Irure est ex velit velit culpa incididunt ullamco excepteur enim fugiat. Dolore commodo pariatur fugiat elit.",
           "Laborum occaecat culpa ad eiusmod dolore incididunt nisi. Esse anim qui est cupidatat eiusmod et tempor sint aliqua. Et pariatur nostrud ad anim minim mollit consectetur quis irure ad. Aliquip incididunt anim non officia officia ut aute fugiat ullamco esse nisi. Minim anim ea ad voluptate eu amet est. Ea et officia ullamco proident aliquip ullamco.",
           "In minim ea labore reprehenderit sit commodo consequat. Sit sit non exercitation in quis ipsum ea anim excepteur. Est cupidatat in ea exercitation adipisicing fugiat proident anim reprehenderit. Irure pariatur amet ut duis consectetur quis deserunt adipisicing labore proident. Pariatur sint nulla consequat in.",
           "Qui occaecat nisi do elit sunt incididunt veniam. Laboris excepteur fugiat Lorem magna proident cillum minim anim. Proident deserunt amet officia occaecat pariatur. Labore irure irure laborum sint nostrud officia laboris id consectetur eiusmod do. Adipisicing elit in ullamco et non qui.",
           "Veniam mollit proident elit sunt reprehenderit deserunt duis id anim pariatur anim. Duis aliqua id velit elit irure elit et nostrud voluptate ex laboris anim cillum. Sunt nisi elit eiusmod excepteur in aute deserunt in sunt. Ad id anim cupidatat irure mollit magna dolore.",
           "Non nisi consectetur reprehenderit do. Proident elit et Lorem excepteur duis. Laboris et labore minim magna duis dolor quis. Fugiat aute anim sit ex incididunt adipisicing consectetur esse anim sunt laborum. Mollit sint do proident minim elit pariatur aliqua velit.",
           "Do adipisicing enim dolore ad eiusmod et excepteur ipsum dolore irure deserunt aute. Irure elit officia commodo exercitation labore laboris ea. Nisi incididunt sint incididunt occaecat labore enim magna pariatur aute ad ad minim mollit. Amet enim ad eu dolor.",
           "Id culpa Lorem cillum ad adipisicing minim velit sit Lorem incididunt laborum cupidatat sunt. Laboris quis eiusmod proident officia consequat nisi. Reprehenderit aliqua commodo culpa laboris quis proident dolore ea ullamco commodo do in consectetur cillum. Velit occaecat est minim anim nisi do qui aliquip exercitation ipsum enim. Ad qui qui dolore nulla mollit minim laboris proident. Dolore magna laborum sint deserunt ex.",
           "Elit mollit aute ea proident. Minim cillum cillum velit consequat pariatur proident. Dolor sit dolore elit velit amet aliqua Lorem sit consequat ex proident. Adipisicing deserunt deserunt aute quis mollit Lorem nulla reprehenderit eu nostrud elit. Cillum cupidatat fugiat ea proident est excepteur dolor non amet consequat magna ipsum proident ipsum.",
           "Consectetur enim aliquip fugiat nisi commodo ad nulla tempor consectetur irure reprehenderit irure. Ea est irure do reprehenderit ex magna et dolore ipsum cillum sunt. Ullamco tempor Lorem magna ut et dolor in magna proident. Deserunt non id consequat consectetur amet sunt laborum mollit esse nostrud non. Mollit deserunt exercitation velit aliqua consectetur nostrud duis sunt eiusmod. Ad eiusmod nostrud dolor consequat exercitation ad consectetur occaecat quis irure eu.",
           "Mollit nostrud exercitation magna non fugiat occaecat et laboris tempor et ad excepteur sit voluptate. Lorem irure anim culpa aliquip sunt ipsum tempor. Nisi velit nostrud aliquip enim irure cillum cillum eiusmod sunt voluptate. Elit anim pariatur labore veniam veniam consectetur magna qui sit. Ullamco fugiat aliqua adipisicing sit magna excepteur sunt tempor laborum duis aute qui ea ullamco.",
           "Ut sit anim aliquip dolore. Magna sunt duis velit in reprehenderit velit minim Lorem sunt ut mollit laborum. Amet ex aliquip pariatur aliquip in excepteur tempor do dolore Lorem. Tempor nisi incididunt deserunt laborum occaecat pariatur pariatur incididunt officia nulla pariatur dolore sint ipsum. Pariatur in anim laboris laborum sit non occaecat cillum incididunt irure ut non excepteur ipsum.",
           "Qui nostrud sit Lorem consectetur pariatur. Incididunt aute eiusmod ut officia. Labore Lorem fugiat laboris voluptate. Aliquip dolor aliqua aliquip magna ipsum elit. Sunt labore duis ad est est culpa et Lorem proident incididunt.",
           "Consequat veniam deserunt officia eu sit laborum tempor ad culpa velit nulla dolore aliqua aute. Occaecat aute dolore eu voluptate. Sit esse sunt culpa excepteur ad. Sit eu esse cillum velit culpa. Occaecat nulla amet voluptate veniam minim culpa aute aliquip ex consequat in irure do. Commodo commodo fugiat sint officia cupidatat nisi consequat ut velit mollit quis quis nulla dolore.",
           "Commodo commodo minim sunt nisi commodo sint magna amet cillum magna. Enim tempor irure consectetur Lorem labore. Do id tempor laborum veniam Lorem laborum deserunt excepteur laborum exercitation minim. Proident ex voluptate eu excepteur ut. Dolore est quis qui mollit et elit quis ad ullamco id ut duis.",
           "Non eu sunt ut officia aliqua non pariatur in. Irure aliqua elit et eu nostrud enim id sit. Sint officia qui nisi sint elit veniam nisi magna officia consequat adipisicing nostrud consectetur. Elit ipsum culpa occaecat fugiat adipisicing.",
           "Aliqua sint sit et laboris. Do nostrud aliqua sunt aliquip minim voluptate reprehenderit esse amet esse deserunt cupidatat cupidatat aute. Excepteur excepteur aute id tempor esse officia culpa eu qui occaecat veniam ad. Sunt pariatur elit nisi in id est adipisicing.",
           "Nisi Lorem id eu officia aute duis amet in et aute deserunt qui occaecat. Irure nisi commodo labore duis id fugiat. Esse id ex eiusmod pariatur ad cillum ad pariatur esse incididunt magna in eiusmod consectetur. Incididunt Lorem proident laborum sunt amet enim dolor nisi nisi aute id non magna. Dolor adipisicing non et est quis veniam est tempor nostrud laboris sit ea. Laborum veniam irure ullamco nulla anim.",
           "Proident eiusmod excepteur consequat voluptate commodo veniam deserunt laborum eiusmod Lorem pariatur aliqua. Sunt anim aute labore officia exercitation officia occaecat irure nostrud veniam sint. Quis sint sint do esse Lorem. Esse adipisicing excepteur amet proident.",
           "Eiusmod cillum aute quis do in quis voluptate elit mollit nostrud id. Nostrud ea deserunt sunt adipisicing velit incididunt. Aliqua ea sit sint irure ullamco. In ea esse nostrud sit esse elit proident velit qui. Veniam enim laborum enim cillum aliquip et aute dolore fugiat consectetur qui. Dolor sint duis veniam sint mollit et ad ad velit velit ipsum laboris. Commodo aliquip exercitation nulla id nulla do sunt cupidatat reprehenderit anim adipisicing non officia.",
           "Anim cupidatat non ut cupidatat tempor id mollit ullamco commodo occaecat voluptate laborum. Dolore excepteur veniam ad anim ad aliqua ad laboris ad magna non aute. Ut est aliquip est laborum cillum. Exercitation ea culpa labore tempor. Sint adipisicing magna eiusmod commodo est labore duis ad laborum laborum esse.",
           "Cillum qui esse deserunt cillum dolore exercitation ipsum nulla duis tempor eiusmod commodo. Adipisicing ad laborum sint cillum elit anim. Excepteur ad ex duis ea velit minim qui nisi. Incididunt esse velit pariatur velit occaecat pariatur irure. Nostrud minim enim commodo ex sint duis consequat esse. Occaecat consectetur magna esse anim labore et magna cillum incididunt duis ipsum nostrud sunt sunt. Est sunt in voluptate laboris nisi ea in ad elit.",
           "Ad sint occaecat do ea cupidatat Lorem occaecat. Exercitation duis ut aute enim mollit cillum elit culpa laborum tempor eiusmod id magna in. Deserunt qui cupidatat aliquip quis veniam voluptate enim ex qui magna. Sunt nostrud cupidatat exercitation deserunt ex proident aute exercitation proident sit Lorem. Et qui minim irure reprehenderit magna dolore aliqua duis elit reprehenderit incididunt.",
           "Cillum qui qui excepteur veniam reprehenderit voluptate ut quis labore consequat in nulla anim incididunt. Aliquip commodo est et reprehenderit laboris. Eu qui labore ipsum sint laborum officia eiusmod.",
           "Aliqua ad adipisicing cillum incididunt quis laboris ullamco incididunt nulla velit esse. Laboris Lorem adipisicing voluptate eiusmod occaecat veniam incididunt dolore. Sit et duis ex laborum officia ullamco sunt commodo cupidatat deserunt adipisicing veniam. Lorem occaecat mollit enim ex.",
           "Ad in sint nostrud officia voluptate sit dolore. Cillum exercitation elit voluptate excepteur exercitation reprehenderit exercitation quis ea aliqua tempor culpa culpa ex. Esse aute voluptate est do reprehenderit laborum pariatur excepteur qui. Dolor consectetur pariatur eu reprehenderit cillum deserunt do exercitation. Qui aliqua cupidatat mollit ad laborum fugiat laboris sit duis esse.",
           "Ipsum culpa mollit id laborum nostrud voluptate magna occaecat. Ex in incididunt ad Lorem anim nostrud officia. Enim id tempor ea aliqua et labore eiusmod.",
           "Occaecat laborum minim veniam eiusmod consequat pariatur ut mollit. Cillum ipsum veniam amet nisi consectetur ut Lorem. Reprehenderit id voluptate voluptate cupidatat cillum nostrud laboris.",
           "Sint nostrud proident aliquip fugiat pariatur ex laborum ipsum culpa consectetur commodo. Officia magna ullamco irure quis et consequat et. Aliquip nisi ea ea nulla enim laborum sint tempor fugiat incididunt officia. Ex do mollit ea reprehenderit ut incididunt sint anim ullamco ea eu ea velit tempor. Tempor officia consequat esse officia magna nulla esse aute.",
           "Culpa velit id reprehenderit velit. Quis qui consequat sint est. Minim deserunt proident irure ullamco. Excepteur eu ut amet minim dolor consectetur. In aute non irure est ex non ut officia incididunt labore nulla aliquip veniam. Laborum proident mollit amet sunt et incididunt laborum sunt.",
           "Mollit quis quis ullamco anim elit excepteur mollit mollit consectetur ad occaecat labore. Laboris sint enim deserunt duis ex quis ad enim voluptate. Excepteur eiusmod nisi dolor non. Fugiat ullamco laboris dolor nisi dolor in esse irure non dolor elit. Lorem id eu mollit sunt labore veniam voluptate laborum nisi proident ea adipisicing cillum non.",
           "Esse mollit adipisicing aute pariatur deserunt in adipisicing minim. Est aliqua veniam anim nostrud cupidatat quis et ullamco aliquip voluptate minim. Reprehenderit ex reprehenderit laborum dolore ut cillum enim culpa reprehenderit consequat commodo nisi minim.",
           "Irure ad aute ea magna consectetur consequat. Cupidatat magna anim voluptate eiusmod. Voluptate proident fugiat duis et exercitation. Sit id non officia excepteur cupidatat incididunt cupidatat qui anim. Occaecat ullamco do officia cillum duis tempor occaecat est laborum culpa mollit non. Magna Lorem eu adipisicing fugiat do cillum velit officia eiusmod voluptate dolor enim pariatur incididunt. Duis consequat fugiat et amet voluptate sit excepteur voluptate ullamco eu ipsum.",
           "Voluptate non ullamco occaecat labore amet mollit incididunt anim fugiat aute ex labore. Commodo nulla aliquip quis voluptate sit est amet veniam Lorem incididunt dolore Lorem excepteur. Ad non amet laborum sit ex. Eiusmod esse ipsum est sunt aliquip enim aute dolore. Irure anim esse labore reprehenderit magna eiusmod labore ipsum cupidatat sit laboris. Laborum non cupidatat Lorem amet reprehenderit cupidatat consectetur id ad proident.",
           "Dolore labore sit officia incididunt occaecat esse nostrud ad duis commodo proident. Officia minim aliquip non culpa nulla aliquip irure. Laboris proident non ea adipisicing laboris minim elit consectetur dolore voluptate nisi esse ea.",
           "Mollit eiusmod exercitation irure laborum nulla culpa eiusmod ex eiusmod incididunt excepteur dolore sint. Et aute laborum ad aute proident nostrud aute. Commodo consequat ea nisi non. Nostrud labore cupidatat nulla elit eiusmod id qui enim.",
           "Nostrud duis minim anim pariatur. Esse ad minim nostrud esse ad. Et do do ut amet nostrud deserunt.",
           "Esse deserunt id qui dolor fugiat ut reprehenderit do et est aute voluptate irure Lorem. Adipisicing laboris nulla adipisicing ullamco aliquip eu id incididunt. Sunt labore consectetur ullamco labore ad id laborum occaecat duis nostrud mollit non.",
           "Consequat eiusmod ad aute culpa aliqua quis nulla deserunt duis. Culpa irure aliquip est ipsum occaecat pariatur incididunt. Pariatur dolor veniam dolore et cupidatat.",
           "Do eu ex excepteur incididunt qui aliquip laborum. Id ea commodo commodo velit tempor sit nostrud. Ullamco anim nulla nulla consequat dolor dolore dolor eiusmod consequat nisi laboris magna. Commodo consequat dolor eu ad aute incididunt enim tempor proident elit. Sint consequat nostrud pariatur officia. Laborum veniam minim sunt ut consequat elit ipsum et ex anim anim laboris. Veniam non commodo in veniam fugiat consequat Lorem laborum sunt velit duis deserunt.",
           "Dolor excepteur ullamco culpa veniam ea esse consequat excepteur veniam culpa dolor veniam incididunt. Enim occaecat officia enim aliquip dolore. Elit nisi adipisicing sunt occaecat do aliqua. Do ut consequat fugiat sit excepteur duis velit ad. Amet est ea ad velit sit. Id consectetur aliqua nostrud proident excepteur exercitation magna labore culpa nulla amet do irure tempor.",
           "Lorem irure ad eiusmod et est laboris id labore. Non exercitation sint cillum minim. Velit sit proident consectetur reprehenderit ipsum. Nisi quis mollit et ipsum Lorem Lorem elit sint ea enim dolor ullamco magna duis. Aute enim laborum anim eiusmod elit. Exercitation voluptate nostrud sunt nostrud do nulla enim esse eiusmod.",
           "Commodo mollit qui Lorem cupidatat occaecat. Magna Lorem deserunt est ipsum sit anim anim. Ex consectetur ullamco eiusmod fugiat adipisicing qui.",
           "Non ex cillum dolore irure excepteur ea. Anim exercitation ullamco officia non nulla culpa proident duis. Duis cupidatat nisi dolore consectetur consectetur ut. Nostrud pariatur dolore magna culpa eiusmod. Sunt aute mollit ex cupidatat aliqua labore. Aute ullamco laborum officia id laborum dolor veniam occaecat do laboris ullamco.",
           "Cupidatat sunt ipsum ea consectetur labore magna occaecat duis dolor occaecat magna irure officia. Commodo dolor eu exercitation nisi nostrud aliqua cupidatat elit deserunt mollit occaecat voluptate voluptate. Qui reprehenderit id aliqua aute excepteur aliqua est commodo culpa deserunt tempor. Proident adipisicing sit voluptate nulla dolor nostrud deserunt dolor anim magna cupidatat qui Lorem. Et in officia proident officia mollit magna magna mollit aliquip cupidatat occaecat.",
           "Sunt irure eu aute consectetur dolor cupidatat minim id enim elit proident in excepteur. Veniam qui ea quis irure sint commodo. Magna sint dolor ipsum do labore ad. Irure commodo ut ut labore laboris. Nisi velit pariatur irure dolore Lorem culpa. Irure irure magna laboris laboris anim officia ad officia anim exercitation ullamco irure.",
           "Enim in ex do sit pariatur velit excepteur amet minim proident eiusmod veniam. Anim dolore non labore ullamco fugiat proident cillum ipsum. Elit pariatur aliquip deserunt reprehenderit veniam aliquip Lorem enim tempor ipsum ad irure mollit incididunt. Ex cillum ad enim nisi anim consequat tempor.",
           "Deserunt qui culpa ullamco do pariatur id velit non amet. Aliquip voluptate enim aliqua proident laborum et. Sit non id labore est voluptate velit. Fugiat amet ea anim consectetur duis aute dolor id ex mollit minim proident ipsum. Cillum nulla consectetur sunt ut do enim. Elit fugiat Lorem duis laborum laboris dolor aliquip esse minim aliqua enim officia sint velit. Consectetur pariatur reprehenderit nulla et nulla incididunt incididunt sint minim non.",
           "Aliqua ipsum reprehenderit sunt ad laborum aliquip id quis cillum. Magna qui proident fugiat exercitation ea officia est enim nulla. Dolore laboris eiusmod non quis est aute tempor commodo aute sint tempor laboris. Magna voluptate ea ullamco laboris consectetur tempor quis et fugiat ea. Dolore officia anim nisi in voluptate reprehenderit pariatur aute adipisicing magna cupidatat occaecat sunt. Laborum magna sunt Lorem velit irure ullamco quis aliquip tempor in.",
           "Laboris pariatur labore elit velit occaecat ut consectetur in exercitation fugiat eu elit. Et mollit irure et deserunt in nostrud deserunt pariatur ipsum velit nostrud enim aute ullamco. Eu enim in eiusmod mollit aliquip fugiat duis tempor incididunt cillum proident ex consequat sint. Sint cupidatat incididunt anim esse nisi consequat nisi cupidatat in laboris qui officia consequat. Ipsum tempor eiusmod ut non quis ea officia. Ad deserunt eiusmod irure proident proident aliquip eiusmod adipisicing.",
           "Non ex tempor minim pariatur. Incididunt veniam id esse non exercitation. Ad culpa culpa minim magna.",
           "Adipisicing aute amet tempor aliqua mollit aliquip. Tempor et cillum consequat dolor occaecat pariatur magna et irure adipisicing nulla magna incididunt. Deserunt laborum ea excepteur reprehenderit. Pariatur sunt sit veniam ad duis elit dolor laborum commodo cupidatat exercitation aute. Aute commodo ipsum amet occaecat eu elit proident aute officia. Veniam adipisicing nisi occaecat dolore do dolore aliquip do magna irure mollit dolore veniam occaecat.",
           "Dolor ipsum eiusmod eu sunt. Ea dolor nisi deserunt dolore ullamco sunt anim non aliqua aute excepteur. Magna nostrud sint ad mollit culpa. Id labore nostrud ad enim quis labore cillum mollit ex voluptate. Ipsum aute proident Lorem sunt eiusmod sint quis.",
           "Ipsum consectetur veniam consequat amet minim qui. Tempor eu officia cupidatat nisi minim ut ullamco. Et aliqua eu id occaecat excepteur dolore ad ullamco. Id nostrud sunt pariatur consequat officia excepteur. Sint minim cillum id incididunt ullamco sint elit qui.",
           "Officia ullamco ullamco proident et. Adipisicing ea consectetur labore pariatur officia. Amet id do nulla non eiusmod. Ut quis velit tempor commodo veniam cillum. Ut laboris consectetur incididunt magna dolor quis fugiat eiusmod. Incididunt sunt ut ipsum consequat elit dolore duis consequat amet. Ad magna ad proident ex qui anim minim veniam.",
           "Incididunt cillum occaecat velit duis adipisicing laboris eiusmod. Ipsum dolore dolor tempor cupidatat. Officia eu fugiat aliqua laboris quis excepteur proident sit quis.",
           "Veniam occaecat consequat sit laborum officia nostrud ad amet fugiat adipisicing id culpa exercitation cupidatat. Velit laboris consequat minim dolor nostrud nulla commodo exercitation elit enim anim commodo duis exercitation. Nostrud in elit ut ut fugiat nisi eu laboris aliqua. Aute Lorem non laborum occaecat deserunt. Elit elit fugiat consectetur mollit aliqua do ea labore cillum exercitation qui dolor.",
           "Do cupidatat id mollit officia sit veniam nisi sunt. Anim dolore mollit enim incididunt commodo cillum elit. Id non nulla incididunt exercitation ad ea occaecat veniam proident elit non reprehenderit veniam velit. Labore aliqua mollit officia ipsum. Proident ea eiusmod tempor ex.",
           "Proident aliquip cupidatat labore deserunt culpa est est. Aute qui occaecat sint incididunt nulla est duis aute labore proident. Esse ea do qui fugiat excepteur voluptate elit proident exercitation ad dolore nostrud. Aliqua dolore consectetur ex pariatur sint veniam magna.",
           "Fugiat elit eu ea aliqua pariatur et laboris dolor cupidatat anim cupidatat. Sint dolore voluptate proident dolore deserunt minim do nostrud minim non consequat irure non. Laborum sit pariatur est incididunt ipsum anim exercitation occaecat fugiat in culpa culpa laboris.",
           "Exercitation aliqua commodo sit Lorem exercitation tempor. Officia nostrud dolor minim consectetur duis cupidatat pariatur ad cillum veniam tempor. Do Lorem ex do aute commodo ea cillum deserunt duis voluptate.",
           "Reprehenderit officia elit eu cillum commodo est esse ullamco eu. Adipisicing enim nisi quis nulla exercitation nostrud anim. Ipsum reprehenderit duis ullamco culpa adipisicing aliquip.",
           "Cillum mollit aliquip culpa tempor ut aute laborum est mollit exercitation. Quis in anim qui esse commodo anim mollit eu labore dolor. Minim veniam occaecat minim incididunt. Cillum mollit ea laboris velit aliquip aute incididunt. Elit nulla voluptate non magna velit sit do veniam proident in enim adipisicing est. Excepteur do est veniam nisi est ut ipsum nostrud sunt id non ipsum magna.",
           "Enim consequat voluptate officia veniam commodo. Id eu laboris excepteur dolore. Dolor magna proident adipisicing officia veniam nisi ea veniam voluptate eu. Sit quis laboris cillum proident dolore amet tempor occaecat nostrud.",
           "Nulla consectetur ut do sunt pariatur velit. Proident reprehenderit do cupidatat id. Velit voluptate enim amet nisi qui irure non duis ex.",
           "Voluptate veniam est amet nisi labore ex proident amet aliqua laboris aliquip exercitation qui reprehenderit. Laborum amet occaecat reprehenderit esse irure duis esse dolor pariatur. Minim cillum in laboris qui irure ipsum non. Irure Lorem exercitation anim incididunt officia nisi magna pariatur esse cupidatat Lorem duis nisi.",
           "Tempor deserunt voluptate ex non in in eiusmod quis nostrud occaecat culpa labore nostrud fugiat. Ad excepteur do consequat eiusmod duis sunt. Adipisicing nulla minim tempor occaecat minim magna velit voluptate aliqua aliqua aliquip non. Elit duis voluptate sunt veniam excepteur reprehenderit nisi exercitation aute consectetur enim sit minim.",
           "Consequat laborum aliqua et aliquip culpa velit qui excepteur aute in laboris irure dolor. Consequat occaecat sit ad irure fugiat esse occaecat eiusmod esse sint pariatur nisi esse. Minim occaecat Lorem ipsum pariatur aute dolore anim consectetur enim amet. Deserunt sint nisi consectetur sint excepteur nisi culpa elit. Deserunt elit non laboris ipsum incididunt cillum eu consectetur qui nisi culpa sunt. Cillum pariatur dolor quis id.",
           "Reprehenderit occaecat esse adipisicing adipisicing magna in eu ea. Ex voluptate occaecat do occaecat reprehenderit in nisi. Fugiat culpa occaecat eiusmod occaecat mollit ex in. Occaecat ipsum ipsum cupidatat dolore ea quis commodo. Anim anim cupidatat in quis ullamco ex et fugiat ea adipisicing cupidatat ad minim laborum. Ea nulla est officia occaecat enim qui do dolor.",
           "Laboris sint officia ipsum culpa Lorem nostrud laborum exercitation. Nisi pariatur veniam qui reprehenderit eu mollit non nostrud consequat duis id. Veniam irure incididunt aute sit incididunt deserunt non non cupidatat ipsum nisi velit. Nostrud cillum ea ea commodo dolor aliqua sit cupidatat aliquip. Consectetur occaecat pariatur reprehenderit nulla adipisicing qui. Culpa et commodo laborum exercitation cillum ullamco tempor aliquip duis consequat. Esse mollit deserunt ipsum amet qui do proident occaecat laborum irure esse voluptate magna.",
           "Enim esse excepteur dolor in occaecat ullamco. Tempor sint esse reprehenderit laboris dolore tempor exercitation labore et. Mollit veniam deserunt ullamco consectetur mollit labore dolore duis velit id.",
           "Voluptate consequat ullamco sit duis sint ipsum ex tempor. Consectetur nostrud tempor excepteur minim ipsum. Quis veniam consequat dolor ex fugiat minim amet sit commodo.",
           "Duis irure anim labore sint mollit anim qui ut veniam ex. Est ex adipisicing quis amet ullamco do tempor ex. Deserunt culpa adipisicing proident magna aliqua ipsum cupidatat. Est velit cillum nisi enim proident nostrud laboris labore occaecat do. Ad officia ullamco ipsum voluptate Lorem eu labore veniam nisi elit ex mollit. Amet do enim anim cupidatat occaecat magna.",
           "Consectetur sint excepteur deserunt minim anim ex magna minim duis esse incididunt sit nostrud. Adipisicing laboris elit do tempor sunt. Lorem nulla labore dolore Lorem tempor occaecat voluptate excepteur amet sunt. Culpa ullamco nisi commodo mollit Lorem enim mollit anim veniam cupidatat. Nostrud officia pariatur culpa commodo voluptate. Sit esse id deserunt consectetur.",
           "Sint amet excepteur ipsum ut eu cillum veniam dolore. Velit nisi duis excepteur tempor deserunt qui labore. Non laboris velit voluptate culpa enim ex veniam anim. Qui labore proident dolore ut nostrud ipsum quis minim dolor nulla nulla ullamco. Esse irure fugiat veniam pariatur eiusmod commodo ea est culpa ad nisi duis ipsum.",
           "In dolore minim anim exercitation reprehenderit laboris culpa quis ut. Incididunt quis mollit pariatur fugiat ea irure laboris enim magna. Do qui voluptate amet ipsum occaecat do duis adipisicing ipsum id cupidatat.",
           "Magna ullamco exercitation amet aliquip irure ad aliquip id. Aliquip cillum magna in voluptate magna tempor eiusmod excepteur. Nisi ex aliquip mollit deserunt aliquip consectetur velit voluptate voluptate ad. Laborum do proident ea deserunt sint aute non est aliquip adipisicing officia excepteur esse minim.",
           "Fugiat proident ad aute duis ex sunt laborum et Lorem et in enim adipisicing. Eiusmod enim elit ea quis veniam aliqua dolor aliquip nisi sunt. Nostrud nostrud est consectetur anim nostrud est sit eu aliqua. Veniam consectetur consequat nulla elit consectetur tempor ut laboris. Eu amet ad culpa labore deserunt. Non veniam sunt dolore et deserunt adipisicing consequat cupidatat magna pariatur tempor.",
           "Reprehenderit qui consectetur ea labore officia ipsum sunt mollit reprehenderit ullamco do. Quis sunt ipsum consequat non in ullamco. Minim consequat dolore magna cillum laboris adipisicing consectetur ea aliqua ullamco enim ad incididunt deserunt. Ut voluptate aliqua cillum culpa voluptate irure sint est elit nisi deserunt anim ut. Enim aliqua dolor veniam mollit tempor. Minim aute incididunt sit sit sint aute laborum reprehenderit est reprehenderit nisi velit adipisicing adipisicing. Nisi adipisicing voluptate laborum voluptate ut mollit est laborum culpa ullamco.",
           "Fugiat in pariatur esse duis cupidatat. Eu proident adipisicing laborum veniam id non nisi mollit ea. Deserunt exercitation id ad irure in aute eiusmod dolore velit qui officia. Duis ad enim aliquip deserunt in quis consequat qui quis eiusmod fugiat nulla. Dolor laborum qui veniam commodo. Nulla do cupidatat adipisicing amet consequat.",
           "Officia nulla nisi non laborum magna adipisicing laboris. Nulla ad ad sit nulla et deserunt in aute quis ut. Nisi ea labore anim ut magna elit eu. Laboris pariatur cupidatat magna elit sunt esse laborum aute anim amet.",
           "Fugiat est mollit eiusmod commodo Lorem officia magna duis est dolor magna magna minim ullamco. Excepteur non dolore consequat adipisicing sit id et aliquip pariatur. Aute enim dolore incididunt aliquip laborum adipisicing. Ad qui commodo proident deserunt excepteur consequat officia proident irure consectetur laborum mollit. Duis exercitation sint pariatur pariatur ex ad laboris culpa amet. Adipisicing dolor elit eiusmod ut consectetur incididunt Lorem sit consectetur ipsum id mollit anim.",
           "Occaecat eu reprehenderit id deserunt est tempor qui eiusmod duis. Sit pariatur commodo pariatur commodo cupidatat irure nostrud fugiat quis commodo nostrud. Ad consectetur enim duis labore nulla. Veniam nostrud aliqua id aliqua ullamco adipisicing duis adipisicing veniam dolore ipsum commodo in aliquip.",
           "Sit nostrud eiusmod reprehenderit eu deserunt fugiat consequat fugiat mollit aliqua proident adipisicing quis. Laboris velit qui consequat sint laboris et officia aliqua. Cupidatat ex dolor ea duis cillum sint cillum commodo enim. Irure esse ad consequat in id et. Exercitation velit labore incididunt eu pariatur sint reprehenderit anim labore. Consectetur cillum id aute occaecat consectetur pariatur qui consequat.",
           "Adipisicing anim tempor dolor irure sunt adipisicing. Incididunt nulla mollit do cupidatat magna amet sint dolor eu ipsum. Ad voluptate do anim aliqua eu mollit est ex aliqua dolor mollit pariatur ad. Nulla non consectetur fugiat elit ullamco do velit. Cupidatat aute et proident ipsum velit magna est. Eiusmod culpa ut id consectetur. Ad commodo deserunt incididunt sunt duis incididunt amet qui ut magna nulla sint.",
           "Dolor ut enim reprehenderit consectetur velit Lorem occaecat ea nisi est duis tempor incididunt. Consequat incididunt ea officia Lorem enim culpa excepteur voluptate. Ut qui ullamco do Lorem labore reprehenderit do ullamco laboris pariatur. Qui sit elit excepteur incididunt consectetur commodo excepteur qui laborum veniam ex anim. Id dolore deserunt ut tempor occaecat officia amet. Minim eu adipisicing eu amet magna deserunt nulla ullamco Lorem. Quis duis anim dolor quis aute fugiat minim aliquip cupidatat.",
           "Elit deserunt eu ex esse culpa nostrud elit reprehenderit culpa sint eiusmod. Dolor in id dolore ad dolore reprehenderit minim. Ullamco dolore duis qui do enim cupidatat sunt et. Consequat ipsum ut non nostrud tempor excepteur velit do occaecat.",
           "Sunt pariatur tempor ad pariatur enim. Est aliqua sunt exercitation et mollit. Est id fugiat fugiat minim aliqua ullamco elit dolor anim. Lorem excepteur ad esse anim commodo sunt ex pariatur do proident. Amet nostrud consectetur culpa nulla do pariatur ut velit exercitation. Qui cupidatat id consectetur laboris anim.",
           "Nostrud nostrud eu exercitation qui amet labore ad cupidatat ipsum minim occaecat. Aliqua officia minim est proident ad anim mollit do commodo non et. Qui voluptate nostrud ex aliqua dolor ea aute commodo esse qui id elit.",
           "Enim nostrud id velit dolore mollit magna ad laboris aute eu dolor officia cupidatat laborum. Aliquip laboris laboris commodo amet mollit quis irure. Duis aliqua commodo ex do duis reprehenderit.",
           "Exercitation officia enim velit dolor elit nulla in exercitation. Sunt exercitation Lorem adipisicing mollit voluptate irure Lorem esse anim occaecat ut. Ullamco velit id pariatur aliqua dolor anim commodo officia consequat ex nostrud veniam duis. Deserunt labore velit eu culpa labore excepteur est est deserunt veniam eu. Dolor deserunt enim voluptate labore laborum dolor Lorem duis exercitation aliquip ut.",
           "Occaecat pariatur pariatur consectetur do consectetur esse fugiat. Et voluptate consequat aliquip consectetur tempor non in tempor fugiat commodo culpa quis. Incididunt minim magna enim laborum Lorem. Esse id exercitation deserunt labore culpa consequat laboris tempor anim nisi anim.",
           "Ipsum laborum do officia Lorem culpa ex reprehenderit ullamco officia. Voluptate id qui et pariatur id occaecat Lorem culpa tempor tempor officia do. Laborum laborum irure reprehenderit excepteur ut dolor reprehenderit in velit aliqua excepteur. Exercitation irure duis aliqua aliqua aliquip magna. Fugiat aliqua occaecat commodo do consectetur dolor id magna dolor.",
           "Sit reprehenderit est anim consequat occaecat enim dolor. Ea culpa consectetur aliquip commodo reprehenderit velit culpa proident elit id culpa. Excepteur id anim enim excepteur aliquip cupidatat ex ea ut consequat aliquip in mollit. Aliquip cillum deserunt nisi deserunt incididunt laborum in deserunt proident cillum non eiusmod nulla. Voluptate enim minim Lorem deserunt cillum do. Deserunt ut cupidatat mollit magna do commodo velit eiusmod in enim magna. Eiusmod non quis est in ut.",
           "Reprehenderit pariatur qui nulla labore sunt aliquip aute cupidatat ut ea sint. Id amet eu adipisicing commodo ea mollit proident irure aliquip quis deserunt cillum. Duis ipsum eu dolor Lorem dolore reprehenderit enim anim reprehenderit magna laboris sunt sint. Commodo exercitation deserunt non anim id qui ad sunt adipisicing elit elit amet sit proident.",
           "Fugiat et ea cillum laborum eiusmod quis. Mollit esse ullamco enim nulla reprehenderit id tempor ut excepteur exercitation eiusmod dolor eu. In cupidatat tempor qui nulla ut minim voluptate sit magna. Deserunt veniam deserunt pariatur esse eiusmod labore veniam minim commodo nisi aliqua ex et. Ex eu aute culpa excepteur.",
           "Cupidatat mollit ea ullamco anim. Adipisicing est nostrud pariatur in elit nulla nostrud. Tempor mollit enim occaecat excepteur. Id sint tempor incididunt deserunt laboris cupidatat.",
           "Dolore exercitation enim voluptate excepteur deserunt occaecat eiusmod. Excepteur amet amet ut enim laborum aliquip cupidatat tempor. Ut sint dolore laboris elit voluptate minim dolor occaecat eiusmod. Tempor do ea sit fugiat aute dolore ea id officia et proident magna voluptate. Nulla deserunt cillum et labore.",
           "Tempor magna magna amet mollit deserunt minim. Qui sunt commodo aliqua non. Ullamco in eiusmod in qui fugiat laboris nulla consequat aliquip ipsum Lorem exercitation.",
           "Do sit eiusmod voluptate aliqua nostrud proident aliqua anim aute tempor mollit in nostrud dolor. In id anim sit tempor cupidatat laboris in ad culpa. Amet fugiat incididunt ad laboris deserunt ullamco id dolor velit. Officia dolor do aliquip ex ipsum qui aute duis magna est elit.",
           "Duis incididunt tempor nulla minim laboris mollit cupidatat reprehenderit enim qui ad. Sit officia incididunt cupidatat nostrud. Ipsum aute pariatur dolor duis nostrud minim dolor minim.",
           "Quis anim officia do eu irure aute ex deserunt id. Ad proident enim adipisicing reprehenderit eu sunt dolore esse mollit amet. Elit eu amet cillum enim nisi. Excepteur nostrud velit amet amet eu. Occaecat reprehenderit labore est deserunt velit eiusmod ut qui occaecat proident sunt.",
           "Magna dolor cillum voluptate minim irure eu. Duis sint commodo officia cillum sint. Deserunt ipsum consequat incididunt ex ut deserunt nostrud et ad. Quis mollit ullamco eu sint velit aliquip sit enim voluptate. Duis aliquip nulla eiusmod nostrud aute cupidatat quis.",
           "Sint est sint consectetur duis anim. Veniam irure ipsum ipsum minim cillum ea excepteur sunt qui dolor officia nisi deserunt pariatur. Dolore ex veniam ipsum proident cillum voluptate. Ex Lorem ipsum exercitation eiusmod officia proident excepteur officia id magna ullamco quis. Ut ullamco exercitation deserunt ex ex. Nisi eu exercitation in ut fugiat. Veniam exercitation ullamco officia id.",
           "Aute enim laboris in dolor ipsum ut mollit sit irure fugiat adipisicing. Nulla ad excepteur ad consectetur deserunt fugiat consectetur nulla elit ea sint ea. Incididunt ullamco consectetur dolore veniam velit irure qui amet pariatur. Eu ea duis enim cupidatat in. Sit consectetur aliquip pariatur velit pariatur enim aute et occaecat.",
           "Eiusmod mollit nulla nisi ullamco fugiat ullamco ex commodo deserunt laboris velit velit. Voluptate velit dolor sint nulla commodo elit velit do aliquip laborum qui aute Lorem. Culpa commodo esse pariatur ex ea velit adipisicing ea non dolore occaecat incididunt ipsum. Aute anim duis in tempor. Voluptate adipisicing nulla eu mollit duis cillum voluptate proident.",
           "Non labore amet sunt pariatur elit eiusmod minim amet ut sunt ea reprehenderit commodo. Aliquip commodo dolore magna sit incididunt Lorem laborum ipsum aliquip do ad eiusmod aute. Culpa est labore labore voluptate sint velit. Dolore occaecat nulla dolor ut magna ad laborum sunt ipsum aliquip id elit. Incididunt adipisicing esse esse non qui ut commodo non Lorem ex ad eu Lorem labore. Cillum aliquip ipsum occaecat ipsum eiusmod est proident occaecat deserunt laboris."])

(def INTERVAL 600)

(def app-state (reagent/atom {:search nil}))

(def timeout-id (atom nil))

(defn home-page [d]
  (let [search-term  (:search @app-state)]
    [:div
     [:form.form-inline
      [:div.form-group
       [:label "Search"]
       [:input.form-control {:type "text"
                             :on-change (fn [e]
                                          (let [v  (-> e .-target .-value)]
                                            (.clearTimeout d @timeout-id)
                                            (swap! timeout-id (fn [_]
                                                                (.setTimeout d
                                                                             (fn []
                                                                               (reset! timeout-id nil)
                                                                               (swap! app-state assoc :search v))
                                                                             INTERVAL)))))}]]]
     (when-not (string/blank? search-term)
       [:h4 (str "Current Search term: " search-term)])
     [:div
      [:ul
       (for [d  data
             :when (if (string/blank? search-term)
                     true
                     (gstring/caseInsensitiveContains d search-term))]
         ^{:key d} [:li [:span d]])]]]))

(def home-page-component (reagent/create-class {:render (fn [d]
                                                          [home-page d])
                                                :mixins #js [TimerMixin]}))

(defn mount-root
  []
  (reagent/render [home-page-component] (.getElementById js/document "app")))

(defn init!
  []
  (mount-root))
